Refactoring et upgrade 2.1.26-final L'upgrade depuis la précédente version a été testé, mais une sauvegarde préalable n'est pas inutile

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,33 +1,75 @@
 #!/bin/bash
 
-# Récupère les infos de l'application.
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e _common.sh ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/_common.sh ./_common.sh
+	sudo chmod a+rx _common.sh
+fi
+source _common.sh
+source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
 app=$YNH_APP_INSTANCE_NAME
 
-# Source app helpers
-source /usr/share/yunohost/helpers
 final_path=$(ynh_app_setting_get $app final_path)
 domain=$(ynh_app_setting_get $app domain)
+db_name=$(ynh_app_setting_get $app db_name)
 
+#=================================================
+# STANDARD BACKUP STEPS
+#=================================================
+# BACKUP OF THE MAIN DIR OF THE APP
+#=================================================
 
-# The parameter $1 is the backup directory location
-# which will be compressed afterward
-backup_dir=$1/apps/$app
-sudo mkdir -p "$backup_dir"
+CHECK_SIZE "$final_path"
+ynh_backup "$final_path" "${YNH_APP_BACKUP_DIR}$final_path"
 
-# Backup sources & data
-sudo cp -a $final_path/. $backup_dir/sources
+#=================================================
+# BACKUP OF THE NGINX CONFIGURATION
+#=================================================
 
-# Copy Nginx and YunoHost parameters to make the script "standalone"
-sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
-sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf
+ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "${YNH_APP_BACKUP_DIR}/etc/nginx/conf.d/$domain.d/$app.conf"
 
-# Copy dedicated php-fpm process to backup folder
-sudo cp -a /etc/php5/fpm/pool.d/$app.conf $backup_dir/php-fpm.conf
-sudo cp -a /etc/php5/fpm/conf.d/20-$app.ini $backup_dir/php-fpm.ini
+#=================================================
+# BACKUP OF THE PHP-FPM CONFIGURATION
+#=================================================
 
-# Backup db
-root_pwd=$(sudo cat /etc/yunohost/mysql)
-sudo mysqldump -u root -p$root_pwd --no-create-db $app --result-file="$backup_dir/db.sql"
+ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "${YNH_APP_BACKUP_DIR}/etc/php5/fpm/pool.d/$app.conf"
+ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "${YNH_APP_BACKUP_DIR}/etc/php5/fpm/conf.d/20-$app.ini"
 
-# Copie du fichier sk.php
-sudo cp -a /etc/teampass/sk.php $backup_dir/sk.php
+#=================================================
+# BACKUP OF THE SQL BDD
+#=================================================
+
+ynh_mysql_dump_db "$db_name" > db.sql
+CHECK_SIZE "db.sql"
+
+#=================================================
+# SPECIFIC BACKUP
+#=================================================
+# BACKUP SK.PHP
+#=================================================
+
+ynh_backup "/etc/teampass/sk.php" "${YNH_APP_BACKUP_DIR}/etc/teampass/sk.php"
+
+#=================================================
+# BACKUP CRON FILE
+#=================================================
+
+ynh_backup "/etc/cron.d/teampass" "${YNH_APP_BACKUP_DIR}/etc/cron.d/teampass"
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,57 +1,110 @@
 #!/bin/bash
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# Source app helpers
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e _common.sh ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/_common.sh ./_common.sh
+	sudo chmod a+rx _common.sh
+fi
+source _common.sh
 source /usr/share/yunohost/helpers
 
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
+path_url=$(ynh_app_setting_get $app path)
 final_path=$(ynh_app_setting_get $app final_path)
+db_name=$(ynh_app_setting_get $app db_name)
 
-# The parameter $1 is the uncompressed restore directory location
-backup_dir=$1/apps/$app
+#=================================================
+# CHECK IF THE APP CAN BE RESTORED
+#=================================================
 
-# Restore Nginx
-conf=/etc/nginx/conf.d/$domain.d/$app.conf
-if [ -f $conf ]; then
-    echo "There is already a nginx conf file at this path: $conf " >&2
-    ynh_die
-fi
-sudo cp -a $backup_dir/nginx.conf $conf
+sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
+	|| ynh_die "Path not available: ${domain}${path_url}"
+test ! -d $final_path \
+	|| ynh_die "There is already a directory: $final_path "
 
-# Restore YunoHost parameters
-sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
+#=================================================
+# STANDARD RESTORE STEPS
+#=================================================
+# RESTORE OF THE NGINX CONFIGURATION
+#=================================================
 
-# Restore sources & data
-sudo cp -a "$backup_dir/sources/." $final_path
+ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"
 
-# Créer la base de donnée et la restaure
+#=================================================
+# RESTORE OF THE MAIN DIR OF THE APP
+#=================================================
+
+ynh_restore_file "$final_path"
+
+#=================================================
+# RESTORE OF THE SQL BDD
+#=================================================
+
 db_pwd=$(ynh_app_setting_get $app mysqlpwd)
-db_user=$app
-ynh_mysql_create_db $db_user $db_user $db_pwd
-mysql --debug-check -u $db_user -p$db_pwd $db_user < ${backup_dir}/db.sql
+ynh_mysql_setup_db $db_name $db_name $db_pwd
+ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql
 
-# Copy dedicated php-fpm process from backup folder to the right location
-sudo cp -a $backup_dir/php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
-sudo cp -a $backup_dir/php-fpm.ini /etc/php5/fpm/conf.d/20-$app.ini
+#=================================================
+# RECREATE OF THE DEDICATED USER
+#=================================================
 
-# ADD_SYS_USER	# Créer un user système dédié pour l'application
-if ! ynh_system_user_exists "$app"	# Test l'existence de l'utilisateur
-then
-	sudo useradd -d /var/www/$app --system --user-group $app --shell /usr/sbin/nologin || (echo "Unable to create $app system account" >&2 && false)
-fi
+ynh_system_user_create $app	# Recreate the dedicated user, if not exist
 
-# Copie du fichier sk.php
-sudo mkdir /etc/teampass
-sudo cp -a $backup_dir/sk.php /etc/teampass/sk.php
-sudo chown -R root:$app /etc/teampass/sk.php
+#=================================================
+# RESTORE USER RIGHTS
+#=================================================
 
 # Les fichiers appartiennent à root
-sudo chown -R root:$app $final_path
+sudo chown -R root: $final_path
+# Sauf les dossiers files et upload
+sudo chown -R $app: $final_path/files $final_path/upload
 
-# And Reload service
-sudo service php5-fpm reload
+#=================================================
+# RESTORE OF THE PHP-FPM CONFIGURATION
+#=================================================
 
-# Reload webserver
-sudo service nginx reload
+ynh_restore_file "/etc/php5/fpm/pool.d/$app.conf"
+ynh_restore_file "/etc/php5/fpm/conf.d/20-$app.ini"
+
+#=================================================
+# SPECIFIC RESTORE
+#=================================================
+# RESTORE THE SK.PHP FILE
+#=================================================
+
+ynh_restore_file "/etc/teampass/sk.php"
+sudo chown -R root:$app "/etc/teampass/sk.php"
+
+#=================================================
+# RESTORE CRON FILE
+#=================================================
+
+ynh_restore_file "/etc/cron.d/teampass"
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# RELOAD NGINX AND PHP-FPM
+#=================================================
+
+sudo systemctl reload php5-fpm
+sudo systemctl reload nginx
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,53 +1,93 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
-
-# Source app helpers
+source _common.sh
 source /usr/share/yunohost/helpers
 
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
-path=$(ynh_app_setting_get $app path)
+path_url=$(ynh_app_setting_get $app path)
 final_path=$(ynh_app_setting_get $app final_path)
 
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
 
-SETUP_SOURCE "teampass.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
+BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
+ynh_clean_setup () {
+	BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
+}
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
 
-# Delete the install directory.
-SECURE_REMOVE '$final_path/install'
+#=================================================
+# CHECK THE PATH
+#=================================================
 
-# Et copie le fichier de config nginx
-sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
 
-# Modifie les variables dans le fichier de configuration nginx
-sudo sed -i "s@__PATH__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
-sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
-sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf
+#=================================================
+# STANDARD UPGRADE STEPS
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
 
-ADD_SYS_USER	# Créer un user système dédié pour l'application
-POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.
+ynh_setup_source "$final_path"	# Télécharge la source, décompresse et copie dans $final_path
 
-# sudo chown www-data: -R $final_path
-# sudo chmod 770 -R $final_path
-# sudo find $final_path -type f -print0 | xargs -0 sudo chmod 740		# Applique les permissions sur les fichiers seulement (rwxr-----)
-# sudo chmod 770 -R $final_path/files $final_path/upload
-# sudo chmod a+x $final_path/CsvToXml_For_Teampass.sh
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
-# -rw-r--r-- sur les fichiers
-sudo find $final_path -type f -print0 | xargs -0 sudo chmod 644
-# drwxr-xr-x sur les dossiers
-sudo find $final_path -type d -print0 | xargs -0 sudo chmod 755
-# Les dossiers files et upload ont besoin d'un droit d'écriture.
-sudo chmod 774 -R $final_path/files $final_path/upload
-# Le script de conversion csv xml doit être exécutable, au moins par root.
-sudo chmod 744 $final_path/CsvToXml_For_Teampass.sh
+ynh_add_nginx_config
+
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Create the dedicated user, if not exist
+
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
+
+ynh_add_fpm_config	# Créer le fichier de configuration du pool php-fpm et le configure.
+
+#=================================================
+# SPECIFIC UPGRADE
+#=================================================
+# ...
+#=================================================
+
+#=================================================
+# CREATE A CRON FILE FOR AUTOMATIC BACKUP
+#=================================================
+
+echo "0 0 * * 0 $app cd $final_path/backups && php script.backup.php" > /etc/cron.d/teampass
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
+
 # Les fichiers appartiennent à root
 sudo chown -R root: $final_path
+# Sauf les dossiers files et upload
+sudo chown -R $app: $final_path/files $final_path/upload
+# Restreint l'accès au dossier de backup
+sudo chmod 750 $final_path/backups
 
-# Recharge la configuration Nginx
-sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+#=================================================
+# RELOAD NGINX
+#=================================================
+
+sudo systemctl reload nginx
